numpy->> numerical python


In [1]:
import numpy as np

marks=np.array([10,20,30,40,50])

bonus=5

new_marks=bonus+marks
print(new_marks)


[15 25 35 45 55]


In [2]:
a=[2,3,4,5]

a_np=np.array(a)
b_np=a_np*2

print(a_np)
print(b_np)

[2 3 4 5]
[ 4  6  8 10]


In [3]:
arr=[[1,2,3],
     [4,5,6],
     [7,8,9]]
print(arr)
print(type(arr))

n_arr=np.array(arr)
print(n_arr)
print(type(n_arr))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [4]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b=np.ones((5,10))
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.arange(2,6)
print(a)

[2 3 4 5]


In [11]:
an=np.linspace(1,10,5)
print(an)

[ 1.    3.25  5.5   7.75 10.  ]


In [13]:
c=np.array((1,2,3,4))
d=np.array((5,6,7,8))

print(c+d)

[ 6  8 10 12]
